### ISSUE TITLE
Segmentation error - Microsatellite data

### ISSUE THREAD

**Issue by Leah26** [stevemussmann/BayesAss3-SNPs#7]
Hi there, 

I am currently working on microsatellite data consisting of 4 populations with 16 loci. I have previously ran BayesAss on the same data but for 3 populations and it worked perfectly. However, I am not unable to run the data for 4 populations as I am getting an error message stating:

gsl: ../gsl/gsl_rng.h:200: ERROR: invalid n, either 0 or exceeds maximum value of generator. Default GSL error handler invoked. 

I have troubleshooted the program and changed the number of seeds but have still gotten this error. I am aware that is not SNP data but was hoping you might have a solution on how to fix this. 

Below is the attached file.
[Regional_dataset.txt](https://github.com/stevemussmann/BayesAss3-SNPs/files/5627423/Regional_dataset.txt)
 
Kind regards,
Leah.

**Comment by stevemussmann** [comment]
Hi Leah,

If I recall correctly, errors like this are sometimes caused by having missing data for all individuals at a locus in a population, and it looks like there is a lot of missing data in this dataset. At first glance, it appears there may be no data for locus Gf3F3 in the file that you posted, so I would start there for troubleshooting. 

-Steve

**Comment by Leah26** [comment]
Hi Steve,

Thank you so much for your advice, I will definitely try and fix this and
see if it works.

Kind regards,
Leah.
